dependencies:
  
  - smartcontractkit/chainlink-brownie-contracts@0.6.0
  - OpenZeppelin/openzeppelin-contracts@4.6.0


compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.6.0"
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0'
